---
title: "Plots for Presentation"
author: "Heriberto Lopez"
date: "7/7/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(tidyverse)
library(readr) 
library(lubridate)

knitr::opts_chunk$set(echo = TRUE) 

#link for latest dataset
urlfile = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv" 
#reloading dataset 
COVIDdata = read.csv(url(urlfile))  

#Selecting variables of Interest 
COVIDdata <- COVIDdata %>%  
  select(iso_code,location,date, new_cases, new_deaths, people_vaccinated, people_fully_vaccinated, population) 

#Getting familiar with the data 
str(COVIDdata)  

# Reformating the date variable so that it is actually treated as a date 
COVIDdata <- COVIDdata %>% 
  mutate(
    date = as.Date(COVIDdata$date, format = "%Y-%m-%d")
  )
?week()

# Creating a week variable 
COVIDdata <- COVIDdata %>% 
  mutate(
    week = format(date, format = "%Y-%U")
  ) 


special.max = function(x){ #
  ifelse( !all(is.na(x)), max(x, na.rm=T), NA)
}

# Creating new variables for visualization 
COVIDdata %>% 
  group_by(iso_code, location, week, population) %>% 
  summarise(
    new_weekly_cases = sum(new_cases), # new weekly cases variable 
    new_weekly_deaths = sum(new_deaths)) # new weekly deaths variable 
    population = 
    
  )
#
WeeklyCOVIDdata = WeeklyCOVIDdata %>%
  group_by(iso_code, location, week) %>% #groups the weekly data first by location, then by week
  summarise(new_cases_weekly=sum(new_cases), #getting weeklynew cases
            new_deaths_weekly=sum(new_deaths), #getting weekly deaths
            pop_week = special.max(population), #why would I sum population
            ppl_fully_vacc_week = special.max(people_fully_vaccinated), 
            ppl_vacc_week = special.max(people_vaccinated), #these aren't new
            date_week = max(date)) #to allow for the columns to be the same length
#We can change the variables after this point to get the proportions and percentages Dr. Irazarry wanted, or select different columns initially

```

```{r}
view(COVIDdata) 



```

